name: Triggered Workflow
# Controls when the workflow will run
on:

 # Allows you to run this workflow manually from the Actions tab

 repository_dispatch:
    types: [custom-event2]
    inputs:
      dispatch_id:
        description: 'A unique ID provided when dispatching this workflow'
        required: true
        type: string
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 # This workflow contains a single job called "build"
 build:
  name: "job_${{ fromJson(github.event.client_payload.data).dispatch_id }}"
 # The type of runner that the job will run on
  runs-on: ubuntu-latest
 # Steps represent a sequence of tasks that will be executed as part of the job
  steps:
 # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
   - name: ${{ fromJson(github.event.client_payload.data).dispatch_id }}
     run: |
       echo "Dispatch ID: ${{ fromJson(github.event.client_payload.data).dispatch_id }}" >> GITHUB_ENV
     id: capture-dispatch-id

   - uses: actions/checkout@v3
     with:
      ref: ${{ fromJson(github.event.client_payload.data).branch }}
#   - name: Set environment variables
#     run: |
#       echo "RUN_UUID=${{ fromJson(github.event.client_payload.data).RUN_UUID }}" >> $GITHUB_ENV
   - name: Set version and run Appdome build-2secure
     uses: jenseng/dynamic-uses@v1
     with:
       uses: Appdome/github_build-2secure@${{ fromJson(github.event.client_payload.data).VERSION }}
       with: >
         {
           "APPDOME_API_TOKEN": "${{ fromJson(github.event.client_payload.data).APPDOME_API_TOKEN }}",
           "SIGN_OPTIONS": "${{ fromJson(github.event.client_payload.data).SIGN_OPTIONS }}",
           "TEAM-ID": "${{ fromJson(github.event.client_payload.data).TEAM_ID }}",
           "APP_FILE": "${{ fromJson(github.event.client_payload.data).APP_FILE }}",
           "MOBILE_PROVISION_PROFILE_FILE": "${{ fromJson(github.event.client_payload.data).MOBILE_PROVISION_PROFILE_FILE }}",
           "ENTITLEMENTS_FILE": "${{ fromJson(github.event.client_payload.data).ENTITLEMENTS_FILE }}",
           "CERTIFICATE_FILE": "${{ fromJson(github.event.client_payload.data).CERTIFICATE_FILE }}",
           "CERTIFICATE_PASSWORD": "${{ fromJson(github.event.client_payload.data).CERTIFICATE_PASSWORD }}",
           "FUSION_SET_ID": "${{ fromJson(github.event.client_payload.data).FUSION_SET_ID }}",
           "KEYSTORE_FILE": "${{ fromJson(github.event.client_payload.data).KEYSTORE_FILE }}",
           "KEYSTORE_PASSWORD": "${{ fromJson(github.event.client_payload.data).KEYSTORE_PASSWORD }}",
           "KEYSTORE_ALIAS": "${{ fromJson(github.event.client_payload.data).KEYSTORE_ALIAS }}",
           "KEYSTORE_KEY_PASSWORD": "${{ fromJson(github.event.client_payload.data).KEYSTORE_KEY_PASSWORD }}",
           "GOOGLE-PLAY-SIGNING": "${{ fromJson(github.event.client_payload.data).GOOGLE_PLAY_SIGNING }}",
           "SIGN_FINGERPRINT": "${{ fromJson(github.event.client_payload.data).SIGN_FINGERPRINT }}",
            "OUTPUT_APP_NAME": "${{ fromJson(github.event.client_payload.data).OUTPUT_APP_NAME }}"
         }     


   - name: Example of using Appdome secured app
     run: |
        echo ${{ env.APPDOME_SECURED_APP }}
        echo ${{ env.APPDOME_SECURED_APP_SECOND_OUTPUT }}
