name: Reveal Secrets

on: [workflow_dispatch]

jobs:
  reveal-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print Secrets
        run: |
          echo "APPDOME_API_KEY=${{ secrets.APPDOME_API_KEY }}"
          echo "FUSION_SET_ID=${{ secrets.FUSION_SET_ID }}"
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}"
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}"
